[package]
name = "game_of_nim_rust"
version = "0.1.0"
edition = "2021"
license = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.20.1"
crossterm = { version = "0.26" }
